### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by berkorbay** [pjournal/boun01g-data-mine-r-s#2]
Separating preprocessing is good practice but only preprocessing link is active. 

+ [ ] At the beginning explicitly refer to the data source (both external Kaggle link and internal repository link) so readers wouldn't lose time searching for your raw data.
+ [ ] EDA is usually not explanatory but exploratory data analysis. This is a common mistake, don't worry.
+ [ ] Add Kaggle to your references.

**Comment by TahaBayaz** [comment]
> Separating preprocessing is good practice but only preprocessing link is active.
> 
> * [ ]  At the beginning explicitly refer to the data source (both external Kaggle link and internal repository link) so readers wouldn't lose time searching for your raw data.
> * [ ]  EDA is usually not explanatory but exploratory data analysis. This is a common mistake, don't worry.
> * [ ]  Add Kaggle to your references.

Thanks for your feedback. After this feedback:
1. We corrected the EDA link.
2. We added two links of the data which one of them is for Kaggle and the other one is for our Github repository.
3. We corrected the typos.
4. We added the Kaggle as references to our preprocessing.html
